config/routes.rb
Rails.application.routes.draw do
  resources :mortgages

  resources :vendorfinances

  resources :businessinvestments

  resources :properties

  resources :shareportfolios

  resources :termdeposits

  resources :moneyowings

  resources :entities
  get "summary" => "pages#summary"

  resources :cashes

  devise_for :users
  root "pages#summary"
  get "summary" => "pages#summary"
  get "money" =>"entities#money"
  get "moneyOwing" =>"entities#moneyOwing"
  get "groupcash" =>"pages#groupcash"
  get "grouptermdeposit" =>"pages#grouptermdeposit"
   get "groupinvestmentportfolio" =>"pages#groupinvestmentportfolio"
  

end

app/models/businessinvestment.rb
class Businessinvestment < ActiveRecord::Base
end

app/models/cash.rb
class Cash < ActiveRecord::Base

	belongs_to :user
	
end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/models/moneyowing.rb
class Moneyowing < ActiveRecord::Base
end

app/models/mortgage.rb
class Mortgage < ActiveRecord::Base
end

app/models/property.rb
class Property < ActiveRecord::Base
end

app/models/shareportfolio.rb
class Shareportfolio < ActiveRecord::Base
end

app/models/termdeposit.rb
class Termdeposit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cashes
end

app/models/vendorfinance.rb
class Vendorfinance < ActiveRecord::Base
end

app/controllers/cashes_controller.rb
class CashesController < ApplicationController
  before_action :set_cash, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /cashes
  # GET /cashes.json
  def index
    @cashes = Cash.all
  end

  def summary
    @cashes = Cash.all
  end

  # GET /cashes/1
  # GET /cashes/1.json
  def show
  end

  # GET /cashes/new
  def new
    @cash = Cash.new

  end

  # GET /cashes/1/edit
  def edit
  end

  # POST /cashes
  # POST /cashes.json
  def create
    @cash = Cash.new(cash_params)

    respond_to do |format|
      if @cash.save
        format.html { redirect_to @cash, notice: 'Cash was successfully created.' }
        format.json { render :show, status: :created, location: @cash }
      else
        format.html { render :new }
        format.json { render json: @cash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cashes/1
  # PATCH/PUT /cashes/1.json
  def update
    respond_to do |format|
      if @cash.update(cash_params)
        format.html { redirect_to @cash, notice: 'Cash was successfully updated.' }
        format.json { render :show, status: :ok, location: @cash }
      else
        format.html { render :edit }
        format.json { render json: @cash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cashes/1
  # DELETE /cashes/1.json
  def destroy
    @cash.destroy
    respond_to do |format|
      format.html { redirect_to cashes_url, notice: 'Cash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cash
      @cash = Cash.find(params[:id])
    end

    def correct_user
      @cash = current_user.Cash.find_by(id: params[:id])
      redirect_to cashes_path, notice: "Not authorized to edit this Asset" if @cash.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cash_params
      params.require(:cash).permit(:description, :value)
    end
    
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity.all
  end

   def moneyListing
    @entities = Entity.find(:all, :include => :money)
  end

 def summary
    @entities = Entity.all
  end

  def money 
     @entity = Entity.new
  end

  def moneyOwing
     @entity = Entity.new
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities
  # POST /entities.json
  def create
    @entity = Entity.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entity_params
      params.require(:entity).permit(:money, :money_owing, :term_deposit, :share_portfolio, :property, :bus_investment, :vendor_finance, :mortgage, :details, :amount)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
  def home
  end

   
	def summary
    @entities = Entity.all
    @cashes = Cash.all
    @moneyowings = Moneyowing.all
    @termdeposits = Termdeposit.all
    @shareportfolios = Shareportfolio.all
    @properties = Property.all
    @businessinvestments = Businessinvestment.all
     @vendorfinances = Vendorfinance.all
     @mortgages = Mortgage.all
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashes_helper.rb
module CashesHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/moneyowings_helper.rb
module MoneyowingsHelper
end

app/helpers/mortgages_helper.rb
module MortgagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/shareportfolios_helper.rb
module ShareportfoliosHelper
end

app/helpers/termdeposits_helper.rb
module TermdepositsHelper
end

app/helpers/vendorfinances_helper.rb
module VendorfinancesHelper
end

app/views/cashes/_form.html.erb
<%= form_for(@cash) do |f| %>
  <% if @cash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cash.errors.count, "error") %> prohibited this cash from being saved:</h2>

      <ul>
      <% @cash.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table table-hover table-responsive">

  <thead>
  <td><h2>Add Cash</h2></td> 
    <tr>
      <th>Tax Entity</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= f.text_field :description %></td>
        <td>$<%= f.number_field :value %></td>
        <td><div class="actions"><%= f.submit %></td>
      </tr>
  </tbody>

  </table>

  <% end %>

app/views/cashes/edit.html.erb
<h1>Editing Cash</h1>

<%= render 'form' %>

<%= link_to 'Back', @cash %> |

app/views/cashes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current Assets</h1>

<table class="table table-hover table-responsive">

  <thead>
  <td><h2>Cash: $<%= @cashes.sum(:value) %></h2></td>
    <tr>
      <th>Tax Entity</th>
      <th>Prior Year</th>
      <th>Current YTD</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

<% @cashes.each do |cash| %>
      <tr>
        <td><%= cash.description %></td>
        <td>$<%= cash.value %></td>
        <td>$<%= cash.value %></td>
        <td><%= link_to 'View Detail', cash %></td>
        <td></td>
      </tr>

    <% end %>
    
    <tr>
        <td><strong>Total</strong></td>
        
        <td> <strong><%= @cashes.sum(:value) %></strong></td>
        <td><strong><%= @cashes.sum(:value) %></strong></td>
        <td> </td>
      </tr>
    <tr>
      <td><%= link_to 'Back', summary_path %> </td>
      <td></td>
      <td></td>
      <td><%= link_to '+ New Cash', new_cash_path %></td>
    </tr>
  </tbody>
</table>

app/views/cashes/new.html.erb
<h1>New Cash</h1>

<%= render 'form' %>

<%= link_to 'Back', cashes_path %>

app/views/cashes/show.html.erb
 

<h1>Current Assets</h1>

<table class="table table-hover table-responsive">

  <thead>
    <tr>
      <th>Assets</th>
      <th>Tax Entity</th>
      <th>Details</th>
      <th>Prior Year</th>
      <th>Current YTD</th>
      <th>Bank Name</th>
      <th>Account #</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <tr>
    	<td>Cash</td>
        <td><%= @cash.description %></td>
        <td></td>
        <td><%= @cash.value %></td>
        <td><%= @cash.value %></td>
        <td>ANZ</td>
        <td>1234</td>
    </tr>
    <tr>
    <td><%= link_to 'Back', cashes_path %> </td>
    <td></td>
    <td></td>
    <td></td>
   	<td></td>
   	<td></td>
   	<td><%= link_to 'Edit', edit_cash_path(@cash) %> </td>
    </tr>
  </tbody>
</table>
<p id="notice"><%= notice %></p>

app/views/entities/_form.html.erb
<%= form_for(@entity) do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% @entity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :money %><br>
    <%= f.text_field :money %>
  </div>
  <div class="field">
    <%= f.label :money_owing %><br>
    <%= f.text_field :money_owing %>
  </div>
  <div class="field">
    <%= f.label :term_deposit %><br>
    <%= f.text_field :term_deposit %>
  </div>
  <div class="field">
    <%= f.label :share_portfolio %><br>
    <%= f.text_field :share_portfolio %>
  </div>
  <div class="field">
    <%= f.label :property %><br>
    <%= f.text_field :property %>
  </div>
  <div class="field">
    <%= f.label :bus_investment %><br>
    <%= f.text_field :bus_investment %>
  </div>
  <div class="field">
    <%= f.label :vendor_finance %><br>
    <%= f.text_field :vendor_finance %>
  </div>
  <div class="field">
    <%= f.label :mortgage %><br>
    <%= f.text_field :mortgage %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing Entity</h1>

<%= render 'form' %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

app/views/entities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Entities</h1>

<table>
  <thead>
  <h2>Cash</h2>
    <tr>
      <th>Details</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
  </tbody>
</table>

<table>
  <thead>
  <h2>Money Owing</h2>
    <tr>
      <th>Details</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <% @entities.each do |entity, money_owing| %> 
      <tr>
        <td><%= entity.money_owing %></td>
        <td><%= entity.details %></td>
        <td><%= entity.amount %></td>
        <td><%= link_to 'Add Money Owing', money_path %></td>
        <td><%= link_to 'Show', entity %></td>
        <td><%= link_to 'Edit', edit_entity_path(entity) %></td>
        <td><%= link_to 'Destroy', entity, method: :delete, data: { confirm: 'Are you sure?' } %>
      </tr>
      
   <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Money', money_path %>
<%= link_to 'New Entity', new_entity_path %>

app/views/entities/money.html.erb
<%= form_for(@entity) do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% @entity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :money %><br>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entities/moneyOwing.html.erb
<%= form_for(@entity) do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% @entity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :money_owing %><br>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entities/new.html.erb
<h1>New Entity</h1>

<%= render 'form' %>

<%= link_to 'Back', entities_path %>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Money:</strong>
  <%= @entity.money %>
</p>

<p>
  <strong>Money owing:</strong>
  <%= @entity.money_owing %>
</p>

<p>
  <strong>Term deposit:</strong>
  <%= @entity.term_deposit %>
</p>

<p>
  <strong>Share portfolio:</strong>
  <%= @entity.share_portfolio %>
</p>

<p>
  <strong>Property:</strong>
  <%= @entity.property %>
</p>

<p>
  <strong>Bus investment:</strong>
  <%= @entity.bus_investment %>
</p>

<p>
  <strong>Vendor finance:</strong>
  <%= @entity.vendor_finance %>
</p>

<p>
  <strong>Mortgage:</strong>
  <%= @entity.mortgage %>
</p>

<p>
  <strong>Details:</strong>
  <%= @entity.details %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @entity.amount %>
</p>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>