config/routes.rb
Rails.application.routes.draw do
  resources :mortgages

  resources :vendorfinances

  resources :businessinvestments

  resources :properties

  resources :shareportfolios

  resources :termdeposits

  resources :moneyowings

  resources :entities
  get "summary" => "pages#summary"

  resources :cashes

  devise_for :users
  root "pages#summary"
  get "summary" => "pages#summary"
  get "money" =>"entities#money"
  get "moneyOwing" =>"entities#moneyOwing"
  get "groupcash" =>"pages#groupcash"
  get "grouptermdeposit" =>"pages#grouptermdeposit"
   get "groupinvestmentportfolio" =>"pages#groupinvestmentportfolio"
  

end

app/models/businessinvestment.rb
class Businessinvestment < ActiveRecord::Base
end

app/models/cash.rb
class Cash < ActiveRecord::Base

	belongs_to :user
	
end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/models/moneyowing.rb
class Moneyowing < ActiveRecord::Base
end

app/models/mortgage.rb
class Mortgage < ActiveRecord::Base
end

app/models/property.rb
class Property < ActiveRecord::Base
end

app/models/shareportfolio.rb
class Shareportfolio < ActiveRecord::Base
end

app/models/termdeposit.rb
class Termdeposit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cashes
end

app/models/vendorfinance.rb
class Vendorfinance < ActiveRecord::Base
end

app/controllers/cashes_controller.rb
class CashesController < ApplicationController
  before_action :set_cash, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /cashes
  # GET /cashes.json
  def index
    @cashes = Cash.all
  end

  def summary
    @cashes = Cash.all
  end

  # GET /cashes/1
  # GET /cashes/1.json
  def show
  end

  # GET /cashes/new
  def new
    @cash = Cash.new

  end

  # GET /cashes/1/edit
  def edit
  end

  # POST /cashes
  # POST /cashes.json
  def create
    @cash = Cash.new(cash_params)

    respond_to do |format|
      if @cash.save
        format.html { redirect_to @cash, notice: 'Cash was successfully created.' }
        format.json { render :show, status: :created, location: @cash }
      else
        format.html { render :new }
        format.json { render json: @cash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cashes/1
  # PATCH/PUT /cashes/1.json
  def update
    respond_to do |format|
      if @cash.update(cash_params)
        format.html { redirect_to @cash, notice: 'Cash was successfully updated.' }
        format.json { render :show, status: :ok, location: @cash }
      else
        format.html { render :edit }
        format.json { render json: @cash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cashes/1
  # DELETE /cashes/1.json
  def destroy
    @cash.destroy
    respond_to do |format|
      format.html { redirect_to cashes_url, notice: 'Cash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cash
      @cash = Cash.find(params[:id])
    end

    def correct_user
      @cash = current_user.Cash.find_by(id: params[:id])
      redirect_to cashes_path, notice: "Not authorized to edit this Asset" if @cash.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cash_params
      params.require(:cash).permit(:description, :value)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
  def home
  end

   
	def summary
    @entities = Entity.all
    @cashes = Cash.all
    @moneyowings = Moneyowing.all
    @termdeposits = Termdeposit.all
    @shareportfolios = Shareportfolio.all
    @properties = Property.all
    @businessinvestments = Businessinvestment.all
     @vendorfinances = Vendorfinance.all
     @mortgages = Mortgage.all
  	end

end

app/controllers/termdeposits_controller.rb
class TermdepositsController < ApplicationController
  before_action :set_termdeposit, only: [:show, :edit, :update, :destroy]

  # GET /termdeposits
  # GET /termdeposits.json
  def index
    @termdeposits = Termdeposit.all
  end

  def summary
    @termdeposits = Termdeposit.all
  end

  # GET /termdeposits/1
  # GET /termdeposits/1.json
  def show
  end

  # GET /termdeposits/new
  def new
    @termdeposit = Termdeposit.new
  end

  # GET /termdeposits/1/edit
  def edit
  end

  # POST /termdeposits
  # POST /termdeposits.json
  def create
    @termdeposit = Termdeposit.new(termdeposit_params)

    respond_to do |format|
      if @termdeposit.save
        format.html { redirect_to @termdeposit, notice: 'Termdeposit was successfully created.' }
        format.json { render :show, status: :created, location: @termdeposit }
      else
        format.html { render :new }
        format.json { render json: @termdeposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /termdeposits/1
  # PATCH/PUT /termdeposits/1.json
  def update
    respond_to do |format|
      if @termdeposit.update(termdeposit_params)
        format.html { redirect_to @termdeposit, notice: 'Termdeposit was successfully updated.' }
        format.json { render :show, status: :ok, location: @termdeposit }
      else
        format.html { render :edit }
        format.json { render json: @termdeposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /termdeposits/1
  # DELETE /termdeposits/1.json
  def destroy
    @termdeposit.destroy
    respond_to do |format|
      format.html { redirect_to termdeposits_url, notice: 'Termdeposit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_termdeposit
      @termdeposit = Termdeposit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def termdeposit_params
      params.require(:termdeposit).permit(:description, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashes_helper.rb
module CashesHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/moneyowings_helper.rb
module MoneyowingsHelper
end

app/helpers/mortgages_helper.rb
module MortgagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/shareportfolios_helper.rb
module ShareportfoliosHelper
end

app/helpers/termdeposits_helper.rb
module TermdepositsHelper
end

app/helpers/vendorfinances_helper.rb
module VendorfinancesHelper
end

app/views/termdeposits/_form.html.erb
<%= form_for(@termdeposit) do |f| %>
  <% if @termdeposit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@termdeposit.errors.count, "error") %> prohibited this termdeposit from being saved:</h2>

      <ul>
      <% @termdeposit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-hover table-responsive">

  <thead>
  <td><h2>Add Term Deposit</h2></td> 
    <tr>
      <th>Term Deposit Description</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= f.text_field :description %></td>
        <td>$<%= f.number_field :value %></td>
        <td><div class="Actions"><%= f.submit 'Create Term Deposit' %></td>
      </tr>
  </tbody>
</table> 

<% end %>

app/views/termdeposits/edit.html.erb
<h1>Editing Term Deposit</h1>

<%= render 'form' %>

<%= link_to 'Show', @termdeposit %> |
<%= link_to 'Back', termdeposits_path %>

app/views/termdeposits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current Assets</h1>

<table class="table table-hover table-responsive">

  <thead>
  <td><h2>Term Deposit: $<%= @termdeposits.sum(:value) %></h2></td>
    <tr>
      <th>Tax Entity</th>
      <th>Prior Year</th>
      <th>Current YTD</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

  <% @termdeposits.each do |termdeposit| %>
      <tr>
        <td><%= termdeposit.description %></td>
        <td><%= termdeposit.value %></td>
        <td><%= termdeposit.value %></td>
        <td><%= link_to 'View Detail', termdeposit %></td>
        
      </tr>
    <% end %>

      <tr>
        <td><strong>Total</strong></td>
        <td> <strong><%= @termdeposits.sum(:value) %></strong></td>
        <td><strong><%= @termdeposits.sum(:value) %></strong></td>
        <td></td>
      </tr>
  
    <tr>
      <td><%= link_to 'Back', summary_path %> </td>
      <td></td>
      <td></td>
      <td><%= link_to '+ New Term Deposit', new_termdeposit_path %></td>
    </tr>
  </tbody>
</table>




  

app/views/termdeposits/new.html.erb
<h1>New Term Deposit</h1>

<%= render 'form' %>

<%= link_to 'Back', termdeposits_path %>

app/views/termdeposits/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Current Assets</h1>

<table class="table table-hover table-responsive">

  <thead>
    <tr>
      <th>Assets</th>
      <th>Tax Entity</th>
      <th>Details</th>
      <th>Prior Year</th>
      <th>Current YTD</th>
      <th>Bank Name</th>
      <th>Account #</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <tr>
    	<td>Term Deposit</td>
        <td><%= @termdeposit.description %></td>
        <td></td>
        <td><%= @termdeposit.value %></td>
        <td><%= @termdeposit.value %></td>
        <td>ANZ</td>
        <td>1234</td>
    </tr>
    <tr>
    <td><%= link_to 'Back', termdeposits_path %>  </td>
    <td></td>
    <td></td>
    <td></td>
   	<td></td>
   	<td></td>
   	<td><%= link_to 'Edit', edit_termdeposit_path(@termdeposit) %>  </td>
    </tr>
  </tbody>
</table>