config/routes.rb
Rails.application.routes.draw do
  resources :mortgages

  resources :vendorfinances

  resources :businessinvestments

  resources :properties

  resources :shareportfolios

  resources :termdeposits

  resources :moneyowings

  resources :entities
  get "summary" => "pages#summary"

  resources :cashes

  devise_for :users
  root "pages#summary"
  get "summary" => "pages#summary"
  get "money" =>"entities#money"
  get "moneyOwing" =>"entities#moneyOwing"
  get "groupcash" =>"pages#groupcash"
  get "grouptermdeposit" =>"pages#grouptermdeposit"
   get "groupinvestmentportfolio" =>"pages#groupinvestmentportfolio"
  

end

app/models/businessinvestment.rb
class Businessinvestment < ActiveRecord::Base
end

app/models/cash.rb
class Cash < ActiveRecord::Base

	belongs_to :user
	
end

app/models/entity.rb
class Entity < ActiveRecord::Base
end

app/models/moneyowing.rb
class Moneyowing < ActiveRecord::Base
end

app/models/mortgage.rb
class Mortgage < ActiveRecord::Base
end

app/models/property.rb
class Property < ActiveRecord::Base
end

app/models/shareportfolio.rb
class Shareportfolio < ActiveRecord::Base
end

app/models/termdeposit.rb
class Termdeposit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cashes
end

app/models/vendorfinance.rb
class Vendorfinance < ActiveRecord::Base
end

app/controllers/cashes_controller.rb
class CashesController < ApplicationController
  before_action :set_cash, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /cashes
  # GET /cashes.json
  def index
    @cashes = Cash.all
  end

  def summary
    @cashes = Cash.all
  end

  # GET /cashes/1
  # GET /cashes/1.json
  def show
  end

  # GET /cashes/new
  def new
    @cash = Cash.new

  end

  # GET /cashes/1/edit
  def edit
  end

  # POST /cashes
  # POST /cashes.json
  def create
    @cash = Cash.new(cash_params)

    respond_to do |format|
      if @cash.save
        format.html { redirect_to @cash, notice: 'Cash was successfully created.' }
        format.json { render :show, status: :created, location: @cash }
      else
        format.html { render :new }
        format.json { render json: @cash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cashes/1
  # PATCH/PUT /cashes/1.json
  def update
    respond_to do |format|
      if @cash.update(cash_params)
        format.html { redirect_to @cash, notice: 'Cash was successfully updated.' }
        format.json { render :show, status: :ok, location: @cash }
      else
        format.html { render :edit }
        format.json { render json: @cash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cashes/1
  # DELETE /cashes/1.json
  def destroy
    @cash.destroy
    respond_to do |format|
      format.html { redirect_to cashes_url, notice: 'Cash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cash
      @cash = Cash.find(params[:id])
    end

    def correct_user
      @cash = current_user.Cash.find_by(id: params[:id])
      redirect_to cashes_path, notice: "Not authorized to edit this Asset" if @cash.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cash_params
      params.require(:cash).permit(:description, :value)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
  def home
  end

   
	def summary
    @entities = Entity.all
    @cashes = Cash.all
    @moneyowings = Moneyowing.all
    @termdeposits = Termdeposit.all
    @shareportfolios = Shareportfolio.all
    @properties = Property.all
    @businessinvestments = Businessinvestment.all
     @vendorfinances = Vendorfinance.all
     @mortgages = Mortgage.all
  	end

end

app/controllers/shareportfolios_controller.rb
class ShareportfoliosController < ApplicationController
  before_action :set_shareportfolio, only: [:show, :edit, :update, :destroy]

  # GET /shareportfolios
  # GET /shareportfolios.json
  def index
    @shareportfolios = Shareportfolio.all
  end
  
  def summary
    @shareportfolios = Shareportfolio.all
  end

  # GET /shareportfolios/1
  # GET /shareportfolios/1.json
  def show
  end

  # GET /shareportfolios/new
  def new
    @shareportfolio = Shareportfolio.new
  end

  # GET /shareportfolios/1/edit
  def edit
  end

  # POST /shareportfolios
  # POST /shareportfolios.json
  def create
    @shareportfolio = Shareportfolio.new(shareportfolio_params)

    respond_to do |format|
      if @shareportfolio.save
        format.html { redirect_to @shareportfolio, notice: 'Shareportfolio was successfully created.' }
        format.json { render :show, status: :created, location: @shareportfolio }
      else
        format.html { render :new }
        format.json { render json: @shareportfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shareportfolios/1
  # PATCH/PUT /shareportfolios/1.json
  def update
    respond_to do |format|
      if @shareportfolio.update(shareportfolio_params)
        format.html { redirect_to @shareportfolio, notice: 'Shareportfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @shareportfolio }
      else
        format.html { render :edit }
        format.json { render json: @shareportfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shareportfolios/1
  # DELETE /shareportfolios/1.json
  def destroy
    @shareportfolio.destroy
    respond_to do |format|
      format.html { redirect_to shareportfolios_url, notice: 'Shareportfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shareportfolio
      @shareportfolio = Shareportfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shareportfolio_params
      params.require(:shareportfolio).permit(:description, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashes_helper.rb
module CashesHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/moneyowings_helper.rb
module MoneyowingsHelper
end

app/helpers/mortgages_helper.rb
module MortgagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/shareportfolios_helper.rb
module ShareportfoliosHelper
end

app/helpers/termdeposits_helper.rb
module TermdepositsHelper
end

app/helpers/vendorfinances_helper.rb
module VendorfinancesHelper
end

app/views/shareportfolios/_form.html.erb
<%= form_for(@shareportfolio) do |f| %>
  <% if @shareportfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shareportfolio.errors.count, "error") %> prohibited this shareportfolio from being saved:</h2>

      <ul>
      <% @shareportfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <table class="table table-hover table-responsive">

  <thead>
  <td><h2>Add Investment Portfolio</h2></td> 
    <tr>
      <th>Investment Portfolio Description</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= f.text_field :description %></td>
        <td>$<%= f.number_field :value %></td>
        <td><div class="actions"><%= f.submit "Create Investment Portfolio" %></td>
      </tr>
  </tbody>
</table> 
<% end %>

app/views/shareportfolios/edit.html.erb
<h1>Editing Investment Portfolio</h1>

<%= render 'form' %>

<%= link_to 'Show', @shareportfolio %> |
<%= link_to 'Back', shareportfolios_path %>

app/views/shareportfolios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current Assets</h1>

<table class="table table-hover table-responsive">

  <thead>
  <td><h2>Investment Portfolio: $<%= @shareportfolios.sum(:value) %></h2></td>
  <tr>
      <th>Tax Entity</th>
      <th>Prior Year</th>
      <th>Current YTD</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

  <tbody>

<% @shareportfolios.each do |shareportfolio| %>
      <tr>
        <td><%= shareportfolio.description %></td>
        <td><%= shareportfolio.value %></td>
        <td><%= shareportfolio.value %></td>
        <td><%= link_to 'View Detail', shareportfolio %></td>
        
      </tr>
    <% end %>
    <tr>
        <td><strong>Total</strong></td>
        <td> <strong>$<%= @shareportfolios.sum(:value) %></strong></td>
        <td><strong>$<%= @shareportfolios.sum(:value) %></strong></td>
        <td></td>
      </tr>
    
     <tr>
      <td><%= link_to 'Back', summary_path %> </td>
      <td></td>
      <td></td>
      <td><%= link_to '+ New Investment Portfolio', new_shareportfolio_path %></td>
    </tr>
  </tbody>
</table>

<br>

app/views/shareportfolios/new.html.erb
<h1>New Share Portfolio</h1>

<%= render 'form' %>

<%= link_to 'Back', shareportfolios_path %>

app/views/shareportfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @shareportfolio.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @shareportfolio.value %>
</p>

<%= link_to 'Edit', edit_shareportfolio_path(@shareportfolio) %> |
<%= link_to 'Back', shareportfolios_path %>